server:
  port: 8088
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

application:
  hello: Hello Shanhy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql
